import type { LucideIcon } from 'lucide-react';
import {
  Activity,
  AlertCircle,
  AlertOctagon,
  AlertTriangle,
  Apple,
  Baby,
  Bath,
  BookOpen,
  Brain,
  Bug,
  Calendar,
  Clock,
  Droplet,
  Droplets,
  Eye,
  Flame,
  Flower2,
  Footprints,
  Frown,
  Gauge,
  Grid3x3,
  Hand,
  Heart,
  HelpCircle,
  LayoutGrid,
  Leaf,
  MilkOff,
  Moon,
  PartyPopper,
  Repeat,
  RotateCcw,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Smile,
  Snail,
  Soup,
  Sparkles,
  Star,
  Sun,
  Syringe,
  Thermometer,
  Timer,
  TrendingUp,
  User,
  Users,
  UtensilsCrossed,
  Wind,
  XCircle,
  Zap,
} from 'lucide-react';

/**
 * Explicit registry of the lucide icons referenced by name (as strings) in
 * static data. Importing only these lets the bundler tree-shake the rest of
 * lucide-react instead of pulling the whole library via `import * as Icons`.
 * Unknown names fall back to `HelpCircle` so a stale data string degrades
 * gracefully rather than rendering `undefined` (which crashes React).
 */
const iconMap: Record<string, LucideIcon> = {
  Activity,
  AlertCircle,
  AlertOctagon,
  AlertTriangle,
  Apple,
  Baby,
  Bath,
  BookOpen,
  Brain,
  Bug,
  Calendar,
  Clock,
  Droplet,
  Droplets,
  Eye,
  Flame,
  Flower2,
  Footprints,
  Frown,
  Gauge,
  Grid3x3,
  Hand,
  Heart,
  LayoutGrid,
  Leaf,
  MilkOff,
  Moon,
  PartyPopper,
  Repeat,
  RotateCcw,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Smile,
  Snail,
  Soup,
  Sparkles,
  Star,
  Sun,
  Syringe,
  Thermometer,
  Timer,
  TrendingUp,
  User,
  Users,
  UtensilsCrossed,
  Wind,
  XCircle,
  Zap,
};

export function getLucideIcon(name: string): LucideIcon {
  return iconMap[name] ?? HelpCircle;
}
